# Generated by Django 5.2.11 on 2026-02-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('local_padrao', models.CharField(max_length=200, verbose_name='Local padrão')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('semestre', models.CharField(max_length=10, verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-semestre', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('Semanal', 'Semanal'), ('Periódico', 'Periódico'), ('Esporádico', 'Esporádico')], default='Semanal', max_length=20, verbose_name='Tipo')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Início')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Fim')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local')),
                ('peso_presenca', models.IntegerField(default=1, verbose_name='Peso da presença')),
                ('oficinas', models.ManyToManyField(blank=True, related_name='eventos', to='schedule.oficina', verbose_name='Oficinas')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('oficinas_fixas', models.ManyToManyField(blank=True, related_name='alunos', to='schedule.oficina', verbose_name='Oficinas fixas')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='schedule.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AlocacaoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Previsto', 'Previsto'), ('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Dispensado', 'Dispensado')], default='Previsto', max_length=20, verbose_name='Status')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='schedule.aluno', verbose_name='Aluno')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='schedule.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Alocação / Presença',
                'verbose_name_plural': 'Alocações / Presenças',
                'unique_together': {('evento', 'aluno')},
            },
        ),
    ]
