# Generated by Django 5.2.11 on 2026-02-24 18:01

import django.db.models.deletion
from django.db import migrations, models


def migrate_semestre_data(apps, schema_editor):
    """Create Semestre objects from existing Turma.semestre strings and link them."""
    Turma = apps.get_model('schedule', 'Turma')
    Semestre = apps.get_model('schedule', 'Semestre')
    semestre_map = {}
    for turma in Turma.objects.all():
        nome = turma.semestre_old
        if nome not in semestre_map:
            sem, _ = Semestre.objects.get_or_create(nome=nome)
            semestre_map[nome] = sem
        turma.semestre_new = semestre_map[nome]
        turma.save(update_fields=['semestre_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        # 1. Create Semestre model
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, unique=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['-nome'],
            },
        ),
        # 2. Temporarily set ordering to avoid semestre field resolution issues
        migrations.AlterModelOptions(
            name='turma',
            options={
                'ordering': ['nome'],
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        # 3. Rename old CharField to semestre_old
        migrations.RenameField(
            model_name='turma',
            old_name='semestre',
            new_name='semestre_old',
        ),
        # 4. Add new FK field (nullable temporarily)
        migrations.AddField(
            model_name='turma',
            name='semestre_new',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='turmas',
                to='schedule.semestre',
                verbose_name='Semestre',
            ),
        ),
        # 5. Copy data
        migrations.RunPython(
            migrate_semestre_data,
            migrations.RunPython.noop,
        ),
        # 6. Remove old field
        migrations.RemoveField(
            model_name='turma',
            name='semestre_old',
        ),
        # 7. Rename new field to semestre
        migrations.RenameField(
            model_name='turma',
            old_name='semestre_new',
            new_name='semestre',
        ),
        # 8. Make non-nullable
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='turmas',
                to='schedule.semestre',
                verbose_name='Semestre',
            ),
        ),
        # 9. Set final Meta ordering
        migrations.AlterModelOptions(
            name='turma',
            options={
                'ordering': ['-semestre__nome', 'nome'],
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
    ]
