# Generated by Django 5.2.11 on 2026-02-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_semestre_alter_turma_options_alter_turma_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
    ]
