# Generated by Django 5.2.11 on 2026-02-24 19:00

from django.db import migrations


def semanal_to_periodico(apps, schema_editor):
    Evento = apps.get_model('schedule', 'Evento')
    Evento.objects.filter(tipo='Semanal').update(tipo='Periódico')


def periodico_to_semanal(apps, schema_editor):
    pass  # irreversível — não sabemos quais eram Semanal


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_evento_cancelado'),
    ]

    operations = [
        migrations.RunPython(
            semanal_to_periodico,
            periodico_to_semanal,
        ),
    ]
