# Generated by Django 5.2.11 on 2026-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_semanal_to_periodico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Periódico', 'Periódico'), ('Esporádico', 'Esporádico')], default='Periódico', max_length=20, verbose_name='Tipo'),
        ),
    ]
